### ISSUE TITLE
Installation Labs

### ISSUE THREAD

**Issue by victorsinata** [victorsinata/SEBC#1]
```
Create AWS Instance , stuck on service limit m3.xlarge

```

**Comment by victorsinata** [comment]
```
While waiting for response, succeed trying to create 5 m3.large 

```

**Comment by victorsinata** [comment]
Hi, i'm already create and check the preinstall. 
Right now i can't get the cluster to communicate each other in order to setup MySQL master-replica. T__T

**Comment by mfernest** [comment]
Which version of MySQL have you installed?

**Comment by victorsinata** [comment]
Server version: 5.6.35-log MySQL Community Server (GPL)

**Comment by manojsundaram** [comment]
Double check if you are able to ping one server to the other.
If they are unable to talk to each other, make sure for the aws security group you are using - the inbound and outbound rules on this security group allow all connections.

Several people in the bootcamp had this issue.

**Comment by mfernest** [comment]
Which lab step are you currently working on?

**Comment by victorsinata** [comment]
Sorry for the late progress, mysql replica still not succeed, think of trying install cloudera manager first, but stuck on the scm_prepare_database.sh not working...

**Comment by mfernest** [comment]
Did you install the JDBC connector for MySQL?

**Comment by victorsinata** [comment]
Yes, the cloudera installer on web already up but the installation still failed. 3 node due to low disk space, 2 node failed for heartbeat issue. I'll try to resize the disk at the hotel tonight.

**Comment by victorsinata** [comment]
Installation complete, but comes up with bad health, lots of service were unavailable and bad conditions.
Some of them probably because of IP and hostname stated before installation were still dynamic and unable to reverse-forward lookup... Do the cluster still usable to do next lab job?

**Comment by victorsinata** [comment]
Forget to update, External MySQL DB for Cloudera already created, but still trying to enable replication..
