### ISSUE TITLE
Welcome to SEBC!

### ISSUE THREAD

**Issue by mfernest** [victorsinata/SEBC#2]
This setup looks good, but please be sure Manoj (manojsundaram) has been invited as a Collaborator. You can close this Issue once he has accepted the invitation.

**Comment by victorsinata** [comment]
Thanks sir... by the way,i change my username from **lobakempuk** to **victorsinata** as my real name to prevent any ambiguity. That might made Manoj thinks i'm not attendee of this bootcamp. ^^. I'll resend the collaborator invitation to him.
